---
name: Deploy RDS Aurora Cluster

description: |
    This GitHub Action automates the deployment of an RDS Aurora cluster using Terraform.
    This action will also install Terraform and awscli. It will output the Aurora cluster endpoint.

inputs:
    awscli-version:
        description: Version of the aws cli to use
        # renovate: datasource=github-releases depName=aws/aws-cli
        default: 2.14.52
