name: Check external links

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1 * *"
  pull_request:
    paths:
      - .github/workflows/links.yml

jobs:
  lint:
    name: links-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Get Current Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> "$GITHUB_ENV"

      - name: Restore lychee cache
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
        with:
          path: .lycheecache
          key: "cache-lychee-${{ env.TIMESTAMP }}"
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          fail: true
          args: -c ./lychee-links.toml --base . --cache --max-cache-age 1d . --verbose --no-progress '*.md' './**/*.md'
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Issue From File
        if: failure() && github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue

      - name: Notify in Slack in case of failure
        id: slack-notification
        if: failure() && github.event_name == 'schedule'
        uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@a00d01c8e3225dd7738e864bf9d23deff00004c0 # main
        with:
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
